;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from my-incognito-mode.el

(autoload 'my/incognito-mode "my-incognito-mode"
"Toggle a leak-proof incognito mode that blocks all history and file states." t)
(register-definition-prefixes "my-incognito-mode" '("my/incognito-mode-active"))


;;; Generated autoloads from my-insert-colors.el

(provide 'my-insert-colors)
(register-definition-prefixes "my-insert-colors" '("insert-color" "my-"))


;;; Generated autoloads from my-keybindings.el

(register-definition-prefixes "my-keybindings" '("my-intercept-navigation-map"))


;;; Generated autoloads from my-wordnet.el

(register-definition-prefixes "my-wordnet" '("my-wordnet-lookup" "wordnet-"))


;;; Generated autoloads from nov-consult.el

(autoload 'nov-consult-search "nov-consult"
"Search the current epub for PATTERN using consult.

(fn PATTERN)" t)
(register-definition-prefixes "nov-consult" '("nov-consult-"))


;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
