;;; my-wordnet.el --- Wordnet Dictionary Integration -*- lexical-binding: t; -*-
(require 'cl-lib)

(defun my-wordnet-lookup (word flags)
  "Helper function to run the local wn command, display output, and shift focus."
  (let ((buf (get-buffer-create "*WordNet*"))
        (cmd (format "wn %s %s" word flags)))
    (with-current-buffer buf
      (read-only-mode -1)
      (erase-buffer)
      (insert (format "WordNet Query: %s\n\n" cmd))
      (insert (shell-command-to-string cmd))
      (goto-char (point-min))
      (ansi-color-apply-on-region (point-min) (point-max))
      (view-mode 1))
    (pop-to-buffer buf)))

(defun wordnet-full (word)
  "Prompt for a WORD and a specific WordNet operation with completion, then execute."
  (interactive (list (read-string "Word: " (thing-at-point 'word))))
  (let* ((options
          '(("-over" . "Display overview of all senses of the word in all syntactic categories.")
            ("-synsn" . "Display synonyms and immediate hypernyms (Noun)")
            ("-synsv" . "Display synonyms and immediate hypernyms (Verb)")
            ("-synsa" . "Display synonyms and immediate hypernyms (Adjective)")
            ("-synsr" . "Display synonyms and immediate hypernyms (Adverb)")
            ("-simsv" . "Display verb synonyms grouped by similarity of meaning")
            ("-antsn" . "Display antonyms (Noun)")
            ("-antsv" . "Display antonyms (Verb)")
            ("-antsa" . "Display antonyms (Adjective)")
            ("-antsr" . "Display antonyms (Adverb)")
            ("-famln" . "Display familiarity and polysemy information (Noun)")
            ("-famlv" . "Display familiarity and polysemy information (Verb)")
            ("-famla" . "Display familiarity and polysemy information (Adjective)")
            ("-famlr" . "Display familiarity and polysemy information (Adverb)")
            ("-hypen" . "Recursively display hypernym tree (Noun)")
            ("-hypev" . "Recursively display hypernym tree (Verb)")
            ("-hypon" . "Display immediate hyponyms (Noun)")
            ("-hypov" . "Display immediate hyponyms (Verb)")
            ("-treen" . "Display hyponym tree (Noun)")
            ("-treev" . "Display hyponym tree (Verb)")
            ("-coorn" . "Display the coordinates/sisters (Noun)")
            ("-coorv" . "Display the coordinates/sisters (Verb)")
            ("-derin" . "Display derivational morphology links (Noun)")
            ("-deriv" . "Display derivational morphology links (Verb)")
            ("-domnn" . "Display domain classification (Noun)")
            ("-domnv" . "Display domain classification (Verb)")
            ("-domna" . "Display domain classification (Adjective)")
            ("-domnr" . "Display domain classification (Adverb)")
            ("-domtn" . "Display terms in domain (Noun)")
            ("-domtv" . "Display terms in domain (Verb)")
            ("-domta" . "Display terms in domain (Adjective)")
            ("-domtr" . "Display terms in domain (Adverb)")
            ("-subsn" . "Display substance meronyms (HAS SUBSTANCE)")
            ("-partn" . "Display part meronyms (HAS PART)")
            ("-membn" . "Display member meronyms (HAS MEMBER)")
            ("-meron" . "Display all meronyms (PART, MEMBER, SUBSTANCE)")
            ("-hmern" . "Display meronyms tree recursively")
            ("-sprtn" . "Display part of holonyms (PART OF)")
            ("-smemn" . "Display member of holonyms (MEMBER OF)")
            ("-ssubn" . "Display substance of holonyms (SUBSTANCE OF)")
            ("-holon" . "Display all holonyms (PART, MEMBER, SUBSTANCE OF)")
            ("-hholn" . "Display holonyms tree recursively")
            ("-entav" . "Display entailment relations")
            ("-framv" . "Display applicable verb sentence frames")
            ("-causv" . "Display cause to relations")
            ("-perta" . "Display pertainyms (Adjective)")
            ("-pertr" . "Display pertainyms (Adverb)")
            ("-attrn" . "Display adjective values for noun attribute")
            ("-attra" . "Display noun attributes of adjective values")
            ("-grepn" . "List compound nouns")
            ("-grepv" . "List compound verbs")
            ("-grepa" . "List compound adjectives")
            ("-grepr" . "List compound adverbs")))
         (completion-extra-properties
          `(:annotation-function (lambda (key)
                                   (concat "  --- " (cdr (assoc key ',options))))))
         (choice (completing-read "WordNet Option: " options nil t)))
    (my-wordnet-lookup word choice)))



(defun wordnet-overview (word)
  "Show all senses and definitions for a word (-over)."
  (interactive (list (read-string "Word: " (thing-at-point 'word))))
  (my-wordnet-lookup word "-over"))

(provide 'my-wordnet)
;;; my-wordnet.el ends here
